[package]
name = "impedance-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
poise = "0.5.7"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
